import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT

def generate_pdf(domain, report_text, findings):
    # Output path
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"reconai_{domain}_{timestamp}.pdf"
    output_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "reports")
    os.makedirs(output_dir, exist_ok=True)
    pdf_path = os.path.join(output_dir, filename)

    # Create PDF
    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=letter,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,
        bottomMargin=inch
    )

    # Styles
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Title"],
        fontSize=24,
        textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=10,
        alignment=TA_CENTER
    )

    subtitle_style = ParagraphStyle(
        "SubtitleStyle",
        parent=styles["Normal"],
        fontSize=12,
        textColor=colors.HexColor("#e94560"),
        spaceAfter=5,
        alignment=TA_CENTER
    )

    heading_style = ParagraphStyle(
        "HeadingStyle",
        parent=styles["Heading1"],
        fontSize=14,
        textColor=colors.HexColor("#1a1a2e"),
        spaceBefore=15,
        spaceAfter=8,
        borderPad=5
    )

    body_style = ParagraphStyle(
        "BodyStyle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#333333"),
        spaceAfter=6,
        leading=16
    )

    # Build content
    content = []

    # Header
    content.append(Spacer(1, 0.3 * inch))
    content.append(Paragraph("ReconAI Security Scanner", title_style))
    content.append(Paragraph("Automated Penetration Testing Report", subtitle_style))
    content.append(Spacer(1, 0.2 * inch))
    content.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#e94560")))
    content.append(Spacer(1, 0.2 * inch))

    # Scan Info Table
    scan_info = [
        ["Target Domain", domain],
        ["Scan Date", datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
        ["Report Generated By", "ReconAI + Groq AI"],
        ["Scanner", "Abhishek Sharma - ReconAI v1.0"],
    ]

    info_table = Table(scan_info, colWidths=[2 * inch, 4 * inch])
    info_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
        ("BACKGROUND", (1, 0), (1, -1), colors.HexColor("#f5f5f5")),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("PADDING", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
    ]))
    content.append(info_table)
    content.append(Spacer(1, 0.3 * inch))

    # Vulnerability Summary Table
    content.append(Paragraph("Vulnerability Summary", heading_style))
    content.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cccccc")))
    content.append(Spacer(1, 0.1 * inch))

    vulns = findings["vulnerabilities"]
    critical = len([v for v in vulns if v["severity"] == "CRITICAL"])
    high = len([v for v in vulns if v["severity"] == "HIGH"])
    medium = len([v for v in vulns if v["severity"] == "Medium"])
    info = len([v for v in vulns if v["severity"] in ["Info", "Unknown"]])

    vuln_data = [
        ["Severity", "Count", "Risk Level"],
        ["Critical", str(critical), "Immediate Action Required"],
        ["High", str(high), "Urgent Remediation Needed"],
        ["Medium", str(medium), "Remediate Soon"],
        ["Informational", str(info), "Best Practice"],
    ]

    vuln_table = Table(vuln_data, colWidths=[2 * inch, 1.5 * inch, 3 * inch])
    vuln_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#ffe0e0")),
        ("BACKGROUND", (0, 2), (-1, 2), colors.HexColor("#fff0e0")),
        ("BACKGROUND", (0, 3), (-1, 3), colors.HexColor("#fffde0")),
        ("BACKGROUND", (0, 4), (-1, 4), colors.HexColor("#e0f0ff")),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("PADDING", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("ALIGN", (1, 0), (1, -1), "CENTER"),
    ]))
    content.append(vuln_table)
    content.append(Spacer(1, 0.3 * inch))

    # Subdomains Table
    content.append(Paragraph("Discovered Subdomains", heading_style))
    content.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cccccc")))
    content.append(Spacer(1, 0.1 * inch))

    sub_data = [["Subdomain", "IP Address", "Status"]]
    for s in findings["subdomains"]:
        status = "Alive" if s["is_alive"] else "Dead"
        sub_data.append([
            s["subdomain"],
            s["ip"] or "N/A",
            status
        ])

    sub_table = Table(sub_data, colWidths=[3 * inch, 2 * inch, 1.5 * inch])
    sub_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("PADDING", (0, 0), (-1, -1), 7),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9f9f9")]),
    ]))
    content.append(sub_table)
    content.append(Spacer(1, 0.3 * inch))

    # Open Ports Table
    content.append(Paragraph("Open Ports", heading_style))
    content.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cccccc")))
    content.append(Spacer(1, 0.1 * inch))

    port_data = [["Host", "Port", "Protocol", "Service"]]
    for p in findings["ports"]:
        port_data.append([
            p["host"],
            str(p["port"]),
            p["protocol"],
            p["service"]
        ])

    port_table = Table(port_data, colWidths=[2.5 * inch, 1 * inch, 1.2 * inch, 2 * inch])
    port_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("PADDING", (0, 0), (-1, -1), 7),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9f9f9")]),
    ]))
    content.append(port_table)
    content.append(Spacer(1, 0.3 * inch))

    # AI Generated Report
    content.append(Paragraph("AI Security Analysis", heading_style))
    content.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cccccc")))
    content.append(Spacer(1, 0.1 * inch))

    # Clean and add report text
    for line in report_text.split("\n"):
        line = line.strip()
        if not line:
            content.append(Spacer(1, 0.1 * inch))
        elif line.startswith("###"):
            content.append(Paragraph(line.replace("###", "").strip(), heading_style))
        elif line.startswith("**") and line.endswith("**"):
            bold_style = ParagraphStyle("Bold", parent=body_style, fontName="Helvetica-Bold")
            content.append(Paragraph(line.replace("**", ""), bold_style))
        else:
            try:
                content.append(Paragraph(line, body_style))
            except:
                pass

    # Footer
    content.append(Spacer(1, 0.3 * inch))
    content.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e94560")))
    content.append(Spacer(1, 0.1 * inch))
    content.append(Paragraph(
        "Generated by ReconAI Scanner | Built by Abhishek Sharma | For authorized testing only",
        ParagraphStyle("Footer", parent=body_style, fontSize=8,
                      textColor=colors.gray, alignment=TA_CENTER)
    ))

    # Build PDF
    doc.build(content)
    return pdf_path
